# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def WorkflowChat(self, user_message: str,skills_readme: str,custom_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.WorkflowChat(user_message=user_message,skills_readme=skills_readme,custom_skill_md=custom_skill_md,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="WorkflowChat", args={
                "user_message": user_message,"skills_readme": skills_readme,"custom_skill_md": custom_skill_md,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def WorkflowCodegen(self, user_message: str,plan_json: str,skill_md: str,tool_contracts: str,attempt: int,previous_error: str,previous_code: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.WorkflowCodegen(user_message=user_message,plan_json=plan_json,skill_md=skill_md,tool_contracts=tool_contracts,attempt=attempt,previous_error=previous_error,previous_code=previous_code,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="WorkflowCodegen", args={
                "user_message": user_message,"plan_json": plan_json,"skill_md": skill_md,"tool_contracts": tool_contracts,"attempt": attempt,"previous_error": previous_error,"previous_code": previous_code,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def WorkflowPlan(self, user_message: str,skills_readme: str,skill_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Plan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.WorkflowPlan(user_message=user_message,skills_readme=skills_readme,skill_names=skill_names,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="WorkflowPlan", args={
                "user_message": user_message,"skills_readme": skills_readme,"skill_names": skill_names,
            })
            return typing.cast(types.Plan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def WorkflowPlanReview(self, user_message: str,proposed_plan_json: str,selected_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Plan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.WorkflowPlanReview(user_message=user_message,proposed_plan_json=proposed_plan_json,selected_skill_md=selected_skill_md,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="WorkflowPlanReview", args={
                "user_message": user_message,"proposed_plan_json": proposed_plan_json,"selected_skill_md": selected_skill_md,
            })
            return typing.cast(types.Plan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def WorkflowRespond(self, user_message: str,plan_json: str,executed_code: str,exec_stdout: str,exec_stderr: str,exit_code: int,attempts: int,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.WorkflowRespond(user_message=user_message,plan_json=plan_json,executed_code=executed_code,exec_stdout=exec_stdout,exec_stderr=exec_stderr,exit_code=exit_code,attempts=attempts,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="WorkflowRespond", args={
                "user_message": user_message,"plan_json": plan_json,"executed_code": executed_code,"exec_stdout": exec_stdout,"exec_stderr": exec_stderr,"exit_code": exit_code,"attempts": attempts,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def WorkflowChat(self, user_message: str,skills_readme: str,custom_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="WorkflowChat", args={
            "user_message": user_message,"skills_readme": skills_readme,"custom_skill_md": custom_skill_md,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def WorkflowCodegen(self, user_message: str,plan_json: str,skill_md: str,tool_contracts: str,attempt: int,previous_error: str,previous_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="WorkflowCodegen", args={
            "user_message": user_message,"plan_json": plan_json,"skill_md": skill_md,"tool_contracts": tool_contracts,"attempt": attempt,"previous_error": previous_error,"previous_code": previous_code,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def WorkflowPlan(self, user_message: str,skills_readme: str,skill_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Plan, types.Plan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="WorkflowPlan", args={
            "user_message": user_message,"skills_readme": skills_readme,"skill_names": skill_names,
        })
        return baml_py.BamlStream[stream_types.Plan, types.Plan](
          __result__,
          lambda x: typing.cast(stream_types.Plan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Plan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def WorkflowPlanReview(self, user_message: str,proposed_plan_json: str,selected_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Plan, types.Plan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="WorkflowPlanReview", args={
            "user_message": user_message,"proposed_plan_json": proposed_plan_json,"selected_skill_md": selected_skill_md,
        })
        return baml_py.BamlStream[stream_types.Plan, types.Plan](
          __result__,
          lambda x: typing.cast(stream_types.Plan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Plan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def WorkflowRespond(self, user_message: str,plan_json: str,executed_code: str,exec_stdout: str,exec_stderr: str,exit_code: int,attempts: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="WorkflowRespond", args={
            "user_message": user_message,"plan_json": plan_json,"executed_code": executed_code,"exec_stdout": exec_stdout,"exec_stderr": exec_stderr,"exit_code": exit_code,"attempts": attempts,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def WorkflowChat(self, user_message: str,skills_readme: str,custom_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowChat", args={
            "user_message": user_message,"skills_readme": skills_readme,"custom_skill_md": custom_skill_md,
        }, mode="request")
        return __result__
    async def WorkflowCodegen(self, user_message: str,plan_json: str,skill_md: str,tool_contracts: str,attempt: int,previous_error: str,previous_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowCodegen", args={
            "user_message": user_message,"plan_json": plan_json,"skill_md": skill_md,"tool_contracts": tool_contracts,"attempt": attempt,"previous_error": previous_error,"previous_code": previous_code,
        }, mode="request")
        return __result__
    async def WorkflowPlan(self, user_message: str,skills_readme: str,skill_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowPlan", args={
            "user_message": user_message,"skills_readme": skills_readme,"skill_names": skill_names,
        }, mode="request")
        return __result__
    async def WorkflowPlanReview(self, user_message: str,proposed_plan_json: str,selected_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowPlanReview", args={
            "user_message": user_message,"proposed_plan_json": proposed_plan_json,"selected_skill_md": selected_skill_md,
        }, mode="request")
        return __result__
    async def WorkflowRespond(self, user_message: str,plan_json: str,executed_code: str,exec_stdout: str,exec_stderr: str,exit_code: int,attempts: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowRespond", args={
            "user_message": user_message,"plan_json": plan_json,"executed_code": executed_code,"exec_stdout": exec_stdout,"exec_stderr": exec_stderr,"exit_code": exit_code,"attempts": attempts,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def WorkflowChat(self, user_message: str,skills_readme: str,custom_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowChat", args={
            "user_message": user_message,"skills_readme": skills_readme,"custom_skill_md": custom_skill_md,
        }, mode="stream")
        return __result__
    async def WorkflowCodegen(self, user_message: str,plan_json: str,skill_md: str,tool_contracts: str,attempt: int,previous_error: str,previous_code: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowCodegen", args={
            "user_message": user_message,"plan_json": plan_json,"skill_md": skill_md,"tool_contracts": tool_contracts,"attempt": attempt,"previous_error": previous_error,"previous_code": previous_code,
        }, mode="stream")
        return __result__
    async def WorkflowPlan(self, user_message: str,skills_readme: str,skill_names: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowPlan", args={
            "user_message": user_message,"skills_readme": skills_readme,"skill_names": skill_names,
        }, mode="stream")
        return __result__
    async def WorkflowPlanReview(self, user_message: str,proposed_plan_json: str,selected_skill_md: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowPlanReview", args={
            "user_message": user_message,"proposed_plan_json": proposed_plan_json,"selected_skill_md": selected_skill_md,
        }, mode="stream")
        return __result__
    async def WorkflowRespond(self, user_message: str,plan_json: str,executed_code: str,exec_stdout: str,exec_stderr: str,exit_code: int,attempts: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="WorkflowRespond", args={
            "user_message": user_message,"plan_json": plan_json,"executed_code": executed_code,"exec_stdout": exec_stdout,"exec_stderr": exec_stderr,"exit_code": exit_code,"attempts": attempts,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))